[tool.commitizen]
name = "cz_conventional_commits"
version = "0.11.0"
tag_format = "v$version"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
major_version_zero = true
bump_message = "chore(release): bump version to $new_version"
